# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    volumes:
    - ./data:/var/lib/mysql
    - ./config:/etc/mysql
    - ./log:/var/log
    - ./mysql-files:/var/lib/mysql-files

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
